"""0055 ABDM M2 (HIP) and M3 (HIU) tables.

Revision ID: 0055
Revises: 0054
Create Date: 2026-08-29

Eight tables that make an ABDM exchange auditable end to end. The HIP side
records what we hold, who was allowed to see it, and what we handed over; the
HIU side records what we asked for, on whose authority, and what came back.

Hand-written rather than autogenerated. migrations/env.py imports only some of
the model modules, so `--autogenerate` compares a partial metadata against a
full database and proposes dropping every table it was not shown. That is a
much worse failure than typing the columns out.

Two things are enforced here and not only in the ORM, because the SQLite test
fixture builds schema from ORM metadata and never sees migration-only
constraints (see CLAUDE.md): the status CHECKs, and the paired-nullability of
the HIU private key and its version.
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0055"
down_revision = "0054"
branch_labels = None
depends_on = None

_HI_TYPES = (
    "'OPConsultation','Prescription','DiagnosticReport','DischargeSummary',"
    "'ImmunizationRecord','HealthDocumentRecord','WellnessRecord'"
)


def _pk():
    return sa.Column(
        "id",
        postgresql.UUID(as_uuid=True),
        primary_key=True,
        server_default=sa.text("uuid_generate_v4()"),
    )


def _timestamps():
    return (
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
    )


def _blame():
    return (
        # NOT NULL, matching common/models.py Blame. Declaring it nullable
        # here would let a row exist that the ORM insists cannot.
        sa.Column("created_by", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=False),
        sa.Column("updated_by", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("users.id", ondelete="RESTRICT"), nullable=True),
    )


def _facility():
    return sa.Column(
        "facility_id", postgresql.UUID(as_uuid=True),
        sa.ForeignKey("facilities.id", ondelete="RESTRICT"), nullable=False,
    )


def upgrade() -> None:
    # ---------------------------------------------------------------- HIP (M2)
    op.create_table(
        "abdm_care_contexts",
        _pk(), _facility(),
        sa.Column("patient_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("patients.id", ondelete="RESTRICT"), nullable=False),
        sa.Column("visit_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("visits.id", ondelete="RESTRICT"), nullable=True),
        sa.Column("reference", sa.String(100), nullable=False),
        sa.Column("display", sa.String(200), nullable=False),
        sa.Column("hi_type", sa.String(50), nullable=False),
        *_timestamps(), *_blame(),
        sa.UniqueConstraint("patient_id", "reference",
                            name="uq_abdm_care_context_patient_reference"),
        sa.CheckConstraint(f"hi_type IN ({_HI_TYPES})", name="abdm_care_context_hi_type"),
    )
    op.create_index("ix_abdm_care_contexts_facility_id", "abdm_care_contexts", ["facility_id"])
    op.create_index("ix_abdm_care_contexts_patient_id", "abdm_care_contexts", ["patient_id"])
    # Every FK gets a leading index (the convention
    # test_every_foreign_key_has_a_leading_non_partial_index enforces).
    op.create_index("ix_abdm_care_contexts_visit_id", "abdm_care_contexts", ["visit_id"])
    op.create_index("ix_abdm_care_contexts_created_by", "abdm_care_contexts", ["created_by"])
    op.create_index("ix_abdm_care_contexts_updated_by", "abdm_care_contexts", ["updated_by"])

    op.create_table(
        "abdm_care_context_links",
        _pk(), _facility(),
        sa.Column("patient_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("patients.id", ondelete="RESTRICT"), nullable=False),
        sa.Column("abha_address", sa.String(120), nullable=False),
        sa.Column("link_ref_number", sa.String(120), nullable=True),
        sa.Column("gateway_request_id", sa.String(100), nullable=True),
        sa.Column("status", sa.String(50), nullable=False, server_default="pending"),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        *_timestamps(),
        sa.CheckConstraint("status IN ('pending','confirmed','failed','expired')",
                           name="abdm_link_status"),
    )
    op.create_index("ix_abdm_links_facility_id", "abdm_care_context_links", ["facility_id"])
    op.create_index("ix_abdm_links_abha_address", "abdm_care_context_links", ["abha_address"])
    op.create_index("ix_abdm_links_ref", "abdm_care_context_links", ["link_ref_number"])
    op.create_index("ix_abdm_links_patient_id", "abdm_care_context_links", ["patient_id"])

    op.create_table(
        "abdm_hip_consent_artefacts",
        _pk(), _facility(),
        sa.Column("consent_artefact_id", sa.String(120), nullable=False),
        sa.Column("abha_address", sa.String(120), nullable=False),
        sa.Column("status", sa.String(50), nullable=False, server_default="granted"),
        sa.Column("hi_types", postgresql.JSONB(), nullable=False),
        sa.Column("date_range_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("date_range_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_artefact", postgresql.JSONB(), nullable=False),
        *_timestamps(),
        sa.UniqueConstraint("consent_artefact_id", name="uq_abdm_hip_artefact_id"),
        sa.CheckConstraint("status IN ('granted','revoked','expired')",
                           name="abdm_hip_artefact_status"),
    )
    op.create_index("ix_abdm_hip_artefacts_facility_id", "abdm_hip_consent_artefacts", ["facility_id"])
    op.create_index("ix_abdm_hip_artefacts_abha", "abdm_hip_consent_artefacts", ["abha_address"])

    op.create_table(
        "abdm_hip_hi_requests",
        _pk(), _facility(),
        sa.Column("consent_artefact_id", sa.String(120), nullable=False),
        sa.Column("transaction_id", sa.String(120), nullable=False),
        sa.Column("gateway_request_id", sa.String(100), nullable=True),
        sa.Column("hiu_key_material", postgresql.JSONB(), nullable=False),
        sa.Column("data_push_url", sa.Text(), nullable=False),
        sa.Column("status", sa.String(50), nullable=False, server_default="received"),
        sa.Column("bundles_sent", sa.String(10), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        *_timestamps(),
        sa.UniqueConstraint("transaction_id", name="uq_abdm_hip_hi_transaction"),
        sa.CheckConstraint(
            "status IN ('received','refused','transferring','delivered','failed')",
            name="abdm_hip_hi_status",
        ),
    )
    op.create_index("ix_abdm_hip_hi_facility_id", "abdm_hip_hi_requests", ["facility_id"])

    # ---------------------------------------------------------------- HIU (M3)
    op.create_table(
        "abdm_consent_requests",
        _pk(), _facility(),
        sa.Column("patient_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("patients.id", ondelete="RESTRICT"), nullable=True),
        sa.Column("abha_address", sa.String(120), nullable=False),
        sa.Column("purpose_code", sa.String(50), nullable=False),
        sa.Column("hi_types", postgresql.JSONB(), nullable=False),
        sa.Column("date_range_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("date_range_to", sa.DateTime(timezone=True), nullable=False),
        sa.Column("requested_expiry", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consent_request_id", sa.String(120), nullable=True),
        sa.Column("gateway_request_id", sa.String(100), nullable=True),
        sa.Column("status", sa.String(50), nullable=False, server_default="requested"),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        *_timestamps(), *_blame(),
        sa.CheckConstraint(
            "status IN ('requested','granted','denied','expired','revoked','failed')",
            name="abdm_consent_request_status",
        ),
        sa.CheckConstraint("date_range_to >= date_range_from", name="abdm_consent_request_range"),
    )
    op.create_index("ix_abdm_consent_requests_facility_id", "abdm_consent_requests", ["facility_id"])
    op.create_index("ix_abdm_consent_requests_abha", "abdm_consent_requests", ["abha_address"])
    op.create_index("ix_abdm_consent_requests_patient_id", "abdm_consent_requests", ["patient_id"])
    op.create_index("ix_abdm_consent_requests_created_by", "abdm_consent_requests", ["created_by"])
    op.create_index("ix_abdm_consent_requests_updated_by", "abdm_consent_requests", ["updated_by"])

    op.create_table(
        "abdm_hiu_consent_artefacts",
        _pk(), _facility(),
        sa.Column("consent_request_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("abdm_consent_requests.id", ondelete="RESTRICT"), nullable=False),
        sa.Column("consent_artefact_id", sa.String(120), nullable=False),
        sa.Column("status", sa.String(50), nullable=False, server_default="granted"),
        sa.Column("hi_types", postgresql.JSONB(), nullable=False),
        sa.Column("date_range_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("date_range_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_artefact", postgresql.JSONB(), nullable=False),
        *_timestamps(),
        sa.UniqueConstraint("consent_artefact_id", name="uq_abdm_hiu_artefact_id"),
        sa.CheckConstraint("status IN ('granted','revoked','expired')",
                           name="abdm_hiu_artefact_status"),
    )
    op.create_index("ix_abdm_hiu_artefacts_facility_id", "abdm_hiu_consent_artefacts", ["facility_id"])
    op.create_index("ix_abdm_hiu_artefacts_request", "abdm_hiu_consent_artefacts", ["consent_request_id"])

    op.create_table(
        "abdm_hiu_hi_requests",
        _pk(), _facility(),
        sa.Column("artefact_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("abdm_hiu_consent_artefacts.id", ondelete="RESTRICT"), nullable=False),
        sa.Column("transaction_id", sa.String(120), nullable=True),
        sa.Column("gateway_request_id", sa.String(100), nullable=True),
        sa.Column("status", sa.String(50), nullable=False, server_default="requested"),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("public_key_b64", sa.Text(), nullable=False),
        sa.Column("nonce_b64", sa.Text(), nullable=False),
        sa.Column("private_key_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("key_version", sa.SmallInteger(), nullable=True),
        sa.Column("key_expires_at", sa.DateTime(timezone=True), nullable=False),
        *_timestamps(), *_blame(),
        sa.CheckConstraint(
            "status IN ('requested','acknowledged','received','partial','failed','expired')",
            name="abdm_hiu_hi_status",
        ),
        sa.CheckConstraint(
            "(private_key_encrypted IS NULL) = (key_version IS NULL)",
            name="abdm_hiu_hi_key_pair_consistent",
        ),
    )
    op.create_index("ix_abdm_hiu_hi_facility_id", "abdm_hiu_hi_requests", ["facility_id"])
    op.create_index("ix_abdm_hiu_hi_transaction", "abdm_hiu_hi_requests", ["transaction_id"])
    op.create_index("ix_abdm_hiu_hi_artefact_id", "abdm_hiu_hi_requests", ["artefact_id"])
    op.create_index("ix_abdm_hiu_hi_created_by", "abdm_hiu_hi_requests", ["created_by"])
    op.create_index("ix_abdm_hiu_hi_updated_by", "abdm_hiu_hi_requests", ["updated_by"])

    op.create_table(
        "abdm_received_bundles",
        _pk(), _facility(),
        sa.Column("hi_request_id", postgresql.UUID(as_uuid=True),
                  sa.ForeignKey("abdm_hiu_hi_requests.id", ondelete="RESTRICT"), nullable=False),
        sa.Column("care_context_reference", sa.String(120), nullable=True),
        sa.Column("content_sha256", sa.String(64), nullable=False),
        sa.Column("status", sa.String(50), nullable=False, server_default="stored"),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        *_timestamps(),
        sa.CheckConstraint("status IN ('stored','undecipherable','rejected')",
                           name="abdm_received_bundle_status"),
    )
    op.create_index("ix_abdm_received_bundles_facility_id", "abdm_received_bundles", ["facility_id"])
    op.create_index("ix_abdm_received_bundles_request", "abdm_received_bundles", ["hi_request_id"])


def downgrade() -> None:
    # Reverse dependency order: children before the rows they point at.
    for table in (
        "abdm_received_bundles",
        "abdm_hiu_hi_requests",
        "abdm_hiu_consent_artefacts",
        "abdm_consent_requests",
        "abdm_hip_hi_requests",
        "abdm_hip_consent_artefacts",
        "abdm_care_context_links",
        "abdm_care_contexts",
    ):
        op.drop_table(table)
